<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-i37-9Z1F2P2-w11x64" failures="2" tests="7" name="Test" time="0.174" errors="0" timestamp="2025-03-31T11:35:47 IST">
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test1" time="0.027">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test1" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests.test1(S3_MyTests.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test2" time="0.013">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests.test2(S3_MyTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="ReRun_Failed_TCs_using_IAnnotationTransformer.S3_MyTests" name="test3" time="0.002"/>
</testsuite> <!-- Test -->
